### ISSUE TITLE
Kafka入门

### ISSUE THREAD

**Issue by SaltzmanAlaric** [SaltzmanAlaric/Mirror-blog#63]
> 以下都在**windows(x64)** 环境下运行，前置条件需要安装**JDK** （包括环境变量JAVA_HOME、Classpath和Path），建议安装目录不要有中文或空格。

### 简介

&emsp;&emsp;Kafka是Linkedin于2010年12月份开源的基于zookeeper协调的分布式日志系统（可当作MQ）,它主要用于处理活跃的流式数据，大数据量的数据处理上。目前Kafka已经贡献给Apache基金会并成为顶级开源项目。

&emsp;&emsp;Kafka是一个分布式的消息缓存系统，用于日志处理的分布式消息队列（原本设计的初衷是日志统计分析）。不同于传统MQ，就像redis虽然是内存数据库，但是也可以作为消息队列，但是可靠性差，而且速度太依赖网络IO，适合比较轻量的场合。

<div align=center>

![](https://cdn.jsdelivr.net/gh/SaltzmanAlaric/FigureBed/20200414190057.jpg)

</div>

- 优点：kafka遵从一般的MQ结构，具有高吞吐量（RabbitMQ这方面稍微逊色），副本集机制（实现数据冗余，保证数据不丢失），基于磁盘实现数据的持久化，亚秒级的消息延迟，消息处理的效率很高。

- 缺点：由于是批量发送，所以数据达不到真正的实时；对于mqtt协议不支持；会丢失数据，并且不支持事务；可能会重复消费数据，消息会乱序。

&emsp;&emsp;由于Kafka的特点（分布式：可以任意的扩展，高吞吐量），适合在大数据领域中实时计算以及日志的收集。

---
### 安装

 - Zookeeper安装\
 上[Zookeeper官网](http://zookeeper.apache.org/releases.html#download 'Zookeeper下载页面')下载对应版本。

<div align=center>

![](https://cdn.jsdelivr.net/gh/SaltzmanAlaric/FigureBed/20200414190338.png)

</div>

 解压到本地目录，如`C:\tools\zookeeper-3.6.0`。新建`data`文件夹。\
 进入到`conf`目录，复制`zoo_sample.cfg`为`zoo.cfg`，修改其中`dataDir`为新建文件夹data对的路径，如`C:/tools/zookeeper-3.6.0/data`。（路径使用linux下的正斜杠\/）\
 进入`bin`目录，双击`zkServer.cmd`即可启动zookeeper。
 
 <div align=center>

![](https://cdn.jsdelivr.net/gh/SaltzmanAlaric/FigureBed/20200414190505.png)

</div>
 
 
 - Kafka安装\
 进入[Kafka官网](http://kafka.apache.org/downloads.html 'Kafka下载页面')下载对应版本。

<div align=center>

![](https://cdn.jsdelivr.net/gh/SaltzmanAlaric/FigureBed/20200414190556.png)

</div>

 解压至本地目录，如`C:\tools\kafka_2.11-2.4.1`。新建`logs`文件夹。\
 进入`config`目录，编辑`server.properties`文件，修改`log.dirs`属性部分地址为刚才新建logs文件夹的路径，如`C:/tools/kafka_2.11-2.4.1/logs`。\
 在kafka安装目录`C:\tools\kafka_2.11-2.4.1`下打开cmd命令窗口，输入：
 
```cmd
SET CLASSPATH=.;
```

 然后输入下面的命令启动kafka-server:
 
```cmd
.\bin\windows\kafka-server-start.bat .\config\server.properties
```

<div align=center>

![](https://cdn.jsdelivr.net/gh/SaltzmanAlaric/FigureBed/20200414190622.png)

</div>

---
### 相关概念

<div align=center>

![](https://cdn.jsdelivr.net/gh/SaltzmanAlaric/FigureBed/20200414190733.jpg)

</div>

- 1.Broker：消息中间件处理节点，一个Kafka的server节点就是一个broker，多个broker可以组成一个Kafka集群；

- 2.Topic：一类消息，例如page view日志、click日志等都可以以topic的形式存在，Kafka集群能够同时负责多个topic的分发；

- 3.Partition：topic物理上的分组，一个topic可以分为多个partition，每个partition是一个有序的队；

- 4.Segment：每个partition又由多个segment file组成；
- 5.offset：每个partition都由一系列有序的、不可变的消息组成，这些消息被连续的追加到partition中。partition中的每个消息都有一个连续的序列号叫做offset，用于partition唯一标识一条消息；
- 6.message：这个算是kafka文件中最小的存储单位，即是a commit log。

---
#### Springboot集成

- 添加pom依赖:

```xml
<dependency>
	<groupId>org.springframework.kafka</groupId>
	<artifactId>spring-kafka</artifactId>
</dependency>
```
- yml配置：

```yml
spring:
  kafka:
    # Kafka的服务地址（可以修改kafka安装目录中config\service.properties属性port值，不指定的话，按照默认9092）
    bootstrap-servers: localhost:9092
    producer:
      # 发生错误后，消息重发的次数。
      retries: 0
      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 16384
      # 设置生产者内存缓冲区的大小。
      buffer-memory: 33554432
      # 键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # acks: 0 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks: 1 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks: all 只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: 1
    consumer:
      # 自动提交的时间间隔 在spring boot 2.X 版本中这里采用的是值的类型为Duration 需要符合特定的格式，如1S,1M,2H,5D
      auto-commit-interval: 1S
      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      # latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
      # earliest 在偏移量无效的情况下，消费者将从起始位置读取分区的记录
      auto-offset-reset: earliest
      # 是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false,然后手动提交偏移量
      enable-auto-commit: false
      # 键的反序列化方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 值的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 在侦听器容器中运行的线程数。
      concurrency: 5
      #listner负责ack，每调用一次，就立即commit
      ack-mode: manual_immediate
      missing-topics-fatal: false
```

- 消息生产者

```java
import com.alibaba.fastjson.JSONObject;
import lombok.extern.slf4j.Slf4j;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.support.SendResult;
import org.springframework.stereotype.Component;
import org.springframework.util.concurrent.ListenableFuture;
import org.springframework.util.concurrent.ListenableFutureCallback;

import javax.annotation.Resource;

/**
 */
@Component
@Slf4j
public class Producer {

    @Resource
    private KafkaTemplate<String, Object> template;

    //自定义topic
    public static final String TOPIC_TEST = "topic.test";

    public static final String TOPIC_GROUP1 = "topic.group1";

    public static final String TOPIC_GROUP2 = "topic.group2";

    public void send(Object obj) {
        String obj2String = JSONObject.toJSONString(obj);
        log.info("准备发送消息为：{}", obj2String);
        //发送消息
        ListenableFuture<SendResult<String, Object>> future = template.send(TOPIC_TEST, obj);
        future.addCallback(new ListenableFutureCallback<SendResult<String, Object>>() {
            @Override
            public void onFailure(Throwable throwable) {
                //发送失败的处理
                log.info(TOPIC_TEST + " - 生产者 发送消息失败：" + throwable.getMessage());
            }

            @Override
            public void onSuccess(SendResult<String, Object> stringObjectSendResult) {
                //成功的处理
                log.info(TOPIC_TEST + " - 生产者 发送消息成功：" + stringObjectSendResult.toString());
            }
        });


    }
}
```

- 消息消费者

```java
import lombok.extern.slf4j.Slf4j;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.support.Acknowledgment;
import org.springframework.kafka.support.KafkaHeaders;
import org.springframework.messaging.handler.annotation.Header;
import org.springframework.stereotype.Component;

import java.util.Optional;

/**
 */
@Component
@Slf4j
public class Consumer {

    @KafkaListener(topics = Producer.TOPIC_TEST, groupId = Producer.TOPIC_GROUP1)
    public void topic_test(ConsumerRecord<?, ?> record, Acknowledgment ack, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {

        Optional message = Optional.ofNullable(record.value());
        if (message.isPresent()) {
            Object msg = message.get();
            log.info("topic_test 消费了： Topic:" + topic + ",Message:" + msg);
            ack.acknowledge();
        }
    }

    @KafkaListener(topics = Producer.TOPIC_TEST, groupId = Producer.TOPIC_GROUP2)
    public void topic_test1(ConsumerRecord<?, ?> record, Acknowledgment ack, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {

        Optional message = Optional.ofNullable(record.value());
        if (message.isPresent()) {
            Object msg = message.get();
            log.info("topic_test1 消费了： Topic:" + topic + ",Message:" + msg);
            ack.acknowledge();
        }
    }
}
```

- 测试

```java
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import javax.annotation.Resource;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = Application.class)
public class KafkaTest {

    @Resource
    private Producer producer;

    @Test
    public void test() {
        producer.send("this ia a test kafka topic message!");
    }

}
```

（完）

---
文档信息
---
- 版权声明：自由转载-非商用-非衍生-保持署名（创意共享3.0许可证）
- 转载请注明作者及出处，本文作者为 @SaltzmanAlaric
